name: Flutter CI

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.9'
      - name: Install compiler dependencies
        run: sudo apt-get install -y clang ninja-build libgtk-3-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable linux building
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: localbooru-linux
          directory: build/linux/x64/release/bundle

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.9'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows building
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: localbooru-windows
          directory: build/windows/x64/runner/Release

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.9'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable macOS building
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: localbooru-macos
          directory: build/macos/Build/Products/Release

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.9'
      - name: Install project dependencies
        run: flutter pub get
      - name: Build artifacts
        run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: localbooru-android.apk
          directory: build/app/outputs/flutter-apk/app-release.apk